trigger:
  branches:
    include:
      - "*"
  paths:
    include:
      - ./*
    exclude:
      - ./README.md

pool:
  vmImage: python:3.8

steps:
  - script: pip install -r requirements.txt
    displayName: "Install dependencies"

  - script: robot .
    displayName: "Running Robot Tests"
