trigger:
  branches:
    include:
      - "*"
  paths:
    exclude:
      - ./README.md

pool:
  vmImage: ubuntu-latest
  # vmImage: nikolaik/python-nodejs:python3.9-nodejs20

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"
    displayName: "Install Node.js"

  - script: pip install --upgrade pip && pip install -r requirements.txt
    displayName: "Install dependencies"

  - script: rfbrowser init
    displayName: "Initialize RF Browser"

  - script: robot --xunit xunit.xml --outputdir ./results ./tests
    displayName: "Running Robot Tests"

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: "./results"
      artifact: "results"
      publishLocation: "pipeline"

  # - task: PublishTestResults@2
  #   condition: always()
  #   displayName: "Publish Test Results"
  #   inputs:
  #     testResultsFormat: "XUnit"
  #     testResultsFiles: "**/results/xunit.xml"
  #     testRunTitle: "Robot Framework Test Results"
  #     searchFolder: "$(System.DefaultWorkingDirectory)"
  #     mergeTestResults: true
  #     failTaskOnFailedTests: false
