trigger:
  branches:
    include:
      - "*"
  paths:
    include:
      - ./*
    exclude:
      - ./README.md

pool:
  vmImage: ubuntu-latest
  # vmImage: nikolaik/python-nodejs:python3.9-nodejs20

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"
    displayName: "Install Node.js"

  - script: pip install --upgrade pip && pip install -r requirements.txt
    displayName: "Install dependencies"

  - script: rfbrowser init
    displayName: "Initialize RF Browser"

  - script: robot .
    displayName: "Running Robot Tests"
